import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, ArrowRight, Menu, X, CalendarDays, MapPin, Clock3, ChevronLeft, ChevronRight, Mail, Phone, Send, FlaskConical, Atom, Leaf, UsersRound, Sparkles, Quote } from 'lucide-react';
import './styles.css';
import './dynamic.css';

const events = [
  {type:'Panel', title:'Materials at the Edge', text:'Leaders on the breakthroughs redefining Indian manufacturing.', date:'12 Oct', time:'10:30 AM', place:'Main Auditorium', color:'teal'},
  {type:'Workshop', title:'Materials Characterisation Lab', text:'A hands-on introduction to imaging, testing and interpretation.', date:'12 Oct', time:'02:00 PM', place:'MME Labs', color:'copper'},
  {type:'Seminar', title:'Circular Metals, Real Impact', text:'New systems for resource-aware and resilient industry.', date:'13 Oct', time:'11:15 AM', place:'Seminar Hall', color:'lime'},
  {type:'Competition', title:'The Alloy Challenge', text:'Teams engineer a high-performance material for a real brief.', date:'13 Oct', time:'03:30 PM', place:'Innovation Studio', color:'blue'},
  {type:'Panel', title:'Women in Materials', text:'An honest conversation on the people leading the next era.', date:'14 Oct', time:'10:00 AM', place:'Main Auditorium', color:'rose'},
  {type:'Workshop', title:'Build with Biomaterials', text:'Experiment with nature-inspired systems and smart composites.', date:'14 Oct', time:'01:30 PM', place:'Design Lab', color:'gold'}
];
const schedule = [
 [{time:'09:00', title:'Welcome & registration', meta:'Atrium · Tea & networking', kind:'Open'}, {time:'10:30', title:'Materials at the Edge', meta:'Main Auditorium · Dr. Meera Narayan', kind:'Panel'}, {time:'14:00', title:'Characterisation Lab', meta:'MME Labs · Limited seats', kind:'Workshop'}, {time:'17:00', title:'Faculty & industry mixer', meta:'Terrace Garden', kind:'Social'}],
 [{time:'09:30', title:'Future Materials keynote', meta:'Main Auditorium · Prof. A. Banerjee', kind:'Keynote'}, {time:'11:15', title:'Circular Metals, Real Impact', meta:'Seminar Hall', kind:'Seminar'}, {time:'15:30', title:'The Alloy Challenge', meta:'Innovation Studio', kind:'Competition'}, {time:'18:00', title:'Exhibition walkthrough', meta:'Atrium Gallery', kind:'Open'}],
 [{time:'10:00', title:'Women in Materials', meta:'Main Auditorium', kind:'Panel'}, {time:'13:30', title:'Build with Biomaterials', meta:'Design Lab', kind:'Workshop'}, {time:'16:00', title:'Closing & awards', meta:'Main Auditorium', kind:'Open'}]
];
const speakers = [
  {name:'Dr. Meera Narayan', role:'Chief Scientist', org:'Tata Steel Research', initials:'MN', tone:'speaker-one'},
  {name:'Prof. Arjun Banerjee', role:'Professor of Materials', org:'IIT Kanpur', initials:'AB', tone:'speaker-two'},
  {name:'Nisha Iyer', role:'Co-founder & CEO', org:'Re-Metal Labs', initials:'NI', tone:'speaker-three'},
  {name:'Karthik Rao', role:'Director, Advanced Materials', org:'Mahindra Research', initials:'KR', tone:'speaker-four'}
];
const gallery = [
 ['gallery-a','Microstructures'],['gallery-b','Ideas in motion'],['gallery-c','Inside the lab'],['gallery-d','Making connections'],['gallery-e','Beyond the lecture'],['gallery-f','The details matter']
];
const team = [{name:'Ananya Rao',role:'Overall Coordinator',initials:'AR'},{name:'Dev Sharma',role:'Overall Coordinator',initials:'DS'},{name:'Rhea Menon',role:'Experience & Design',initials:'RM'},{name:'Ishaan Shah',role:'Technical Lead',initials:'IS'}];

function Reveal({children, className=''}) { return <div className={'reveal '+className}>{children}</div> }
function SectionHead({eyebrow, title, children}) { return <Reveal className="section-head"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{children && <p className="lead">{children}</p>}</Reveal> }
function App(){
 const [menu,setMenu]=useState(false), [filter,setFilter]=useState('All'), [day,setDay]=useState(0), [lightbox,setLightbox]=useState(null), [sent,setSent]=useState(false);
 const cats=['All','Panel','Workshop','Seminar','Competition']; const filtered=filter==='All'?events:events.filter(e=>e.type===filter);
 useEffect(()=>{ const obs=new IntersectionObserver((els)=>els.forEach(e=>e.isIntersecting&&e.target.classList.add('show')),{threshold:.08}); document.querySelectorAll('.reveal').forEach(e=>obs.observe(e)); return()=>obs.disconnect() },[]);
 useEffect(()=>{const fn=(e)=>{if(lightbox!==null){if(e.key==='Escape')setLightbox(null);if(e.key==='ArrowRight')setLightbox((lightbox+1)%gallery.length);if(e.key==='ArrowLeft')setLightbox((lightbox-1+gallery.length)%gallery.length)}};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn)},[lightbox]);
 const nav=['About','Events','Schedule','Gallery','Team','Contact']; const jump=(x)=>{setMenu(false);document.getElementById(x.toLowerCase())?.scrollIntoView({behavior:'smooth'})};
 return <><header className="nav"><a className="brand" href="#top" onClick={()=>jump('top')} aria-label="Metallum home"><span className="brand-mark"><span className="mark-orbit orbit-a"></span><span className="mark-orbit orbit-b"></span><Atom size={22}/></span><span>METALLUM<small>MME · 2026</small></span></a><nav>{nav.map(x=><button key={x} onClick={()=>jump(x)}>{x}</button>)}</nav><button className="register mini" onClick={()=>jump('contact')}>Register <ArrowUpRight size={15}/></button><button className="menu" aria-label="Open navigation" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
 {menu&&<div className="mobile-nav">{nav.map(x=><button key={x} onClick={()=>jump(x)}>{x}</button>)}<button className="register" onClick={()=>jump('contact')}>Register now <ArrowUpRight size={16}/></button></div>}
 <main id="top">
 <section className="hero"><div className="grain"></div><div className="hero-copy"><p className="eyebrow">National materials conference · 12—14 Oct</p><h1>The materials<br/><i>that move</i> us.</h1><p className="hero-text">A three-day conversation between students, researchers and industry—exploring the systems, metals and ideas that shape a more resilient world.</p><div className="hero-actions"><button className="register" onClick={()=>jump('contact')}>Reserve your place <ArrowUpRight size={17}/></button><button className="text-button" onClick={()=>jump('about')}>Explore Metallum <ArrowRight size={17}/></button></div></div><figure className="hero-art hero-sculpture"><div className="sculpture-glow"></div><img src="/assets/metallum-sculpture.png" alt="Floating teal glass crystal lattice, silver ribbon and copper sphere"/><figcaption>Metallum / a study in motion</figcaption></figure><div className="scroll-note">SCROLL TO DISCOVER <span></span></div></section>
 <section className="intro"><p>Hosted by the Department of Metallurgical & Materials Engineering</p><div className="stats"><div><b>600<span>+</span></b><small>curious minds</small></div><div><b>18</b><small>voices on stage</small></div><div><b>12</b><small>hands-on sessions</small></div><div><b>08</b><small>institutions together</small></div></div></section>
 <section className="about wrap" id="about"><div className="about-visual"><div className="visual-card"><FlaskConical/><p>Curiosity, made tangible.</p></div><div className="metal-disc"></div><div className="about-caption">/ 01<br/><b>DISCOVER</b></div></div><div className="about-copy"><SectionHead eyebrow="About the conference" title={<>Where deep research meets <em>real possibility.</em></>}>Metallum is our annual meeting point for material thinkers. It brings the lab, the classroom and the shop floor into one purposeful conversation.</SectionHead><p className="body-copy">We are building a programme that is thoughtful, practical and unafraid of hard questions. Come to learn from people doing the work—and leave with collaborators for what comes next.</p><div className="mission"><div><Sparkles/><b>Innovation</b><span>Ideas ready to be tested.</span></div><div><Leaf/><b>Sustainability</b><span>Progress with perspective.</span></div><div><UsersRound/><b>Collaboration</b><span>Better, together.</span></div></div></div></section>
 <section className="events section-tint" id="events"><div className="wrap"><SectionHead eyebrow="The programme" title={<>Find your <em>spark.</em></>}>A considered mix of conversation, experimentation and friendly competition.</SectionHead><div className="filters" role="tablist">{cats.map(c=><button key={c} className={filter===c?'selected':''} onClick={()=>setFilter(c)}>{c}</button>)}</div><div className="event-grid">{filtered.map((e,i)=><article className={'event-card '+e.color} key={e.title}><div className="card-top"><span>{e.type}</span><ArrowUpRight size={20}/></div><div className="event-icon"><span></span></div><h3>{e.title}</h3><p>{e.text}</p><div className="event-meta"><span><CalendarDays/> {e.date}</span><span><Clock3/> {e.time}</span><span><MapPin/> {e.place}</span></div><button onClick={()=>jump('contact')}>Join session <ArrowRight size={15}/></button></article>)}</div></div></section>
 <section className="feature wrap"><div className="feature-art"><div className="feature-ring"></div><div className="feature-ball"></div><p>Featured<br/>experience</p></div><div className="feature-copy"><p className="eyebrow">A signature experience</p><h2>The Alloy<br/><em>Challenge.</em></h2><p>Not just a competition. A live material brief, expert feedback and a room full of people who care about the answer.</p><div className="feature-info"><span>13 OCT · 03:30 PM</span><span>INNOVATION STUDIO</span></div><button className="dark-button" onClick={()=>jump('contact')}>Get the brief <ArrowUpRight size={17}/></button></div></section>
 <section className="schedule wrap" id="schedule"><SectionHead eyebrow="Three days, one shared future" title={<>Make time for the <em>good stuff.</em></>}>Move at your own pace. Save the sessions that make you curious.</SectionHead><div className="day-tabs">{['12 Oct · Day one','13 Oct · Day two','14 Oct · Day three'].map((d,i)=><button key={d} onClick={()=>setDay(i)} className={day===i?'active':''}>{d}</button>)}</div><div className="timeline">{schedule[day].map(x=><div className="slot" key={x.time}><time>{x.time}</time><i></i><div><span>{x.kind}</span><h3>{x.title}</h3><p>{x.meta}</p></div></div>)}</div></section>
 <section className="speakers dark-section"><div className="wrap"><SectionHead eyebrow="Meet the voices" title={<>People with a point of <em>view.</em></>}>A diverse group of researchers, makers and leaders shaping material futures.</SectionHead><div className="speaker-grid">{speakers.map(s=><article className="speaker" key={s.name}><div className={'avatar '+s.tone}>{s.initials}<span></span></div><div><h3>{s.name}</h3><p>{s.role}<br/>{s.org}</p></div><button aria-label={'View '+s.name}><ArrowUpRight size={16}/></button></article>)}</div></div></section>
 <section className="gallery wrap" id="gallery"><SectionHead eyebrow="A living archive" title={<>See what <em>happens next.</em></>}>The moments between the moments, gathered from our community.</SectionHead><div className="masonry">{gallery.map(([c,t],i)=><button className={'gallery-tile '+c} onClick={()=>setLightbox(i)} key={c}><span>{t}</span><ArrowUpRight size={19}/></button>)}</div></section>
 <section className="team section-tint" id="team"><div className="wrap"><SectionHead eyebrow="Our people" title={<>Made by a small, <em>mighty team.</em></>}>Students from the Department of Metallurgical & Materials Engineering, with a healthy obsession for good questions.</SectionHead><div className="team-grid">{team.map((t,i)=><article className="team-card" key={t.name}><div className={'team-avatar t'+i}>{t.initials}</div><h3>{t.name}</h3><p>{t.role}</p><a href="#contact" aria-label={'Contact '+t.name}><ArrowUpRight size={17}/></a></article>)}</div></div></section>
 <section className="partners wrap"><p className="eyebrow">Made possible with</p><div><b>METAL<span>LABS</span></b><b>tata <i>steel</i></b><b>HINDALCO</b><b>ELEMENT<span>42</span></b><b>RE//FORM</b></div></section>
 <section className="contact" id="contact"><div className="wrap contact-grid"><div><p className="eyebrow">Save your seat</p><h2>Bring your<br/><em>curiosity.</em></h2><p>Registration opens soon. Share your details and the team will send the full programme when it is ready.</p><ul><li><Mail/> metallum@mme.edu.in</li><li><Phone/> +91 98200 20426</li><li><MapPin/> Department of MME, India</li></ul></div><form onSubmit={e=>{e.preventDefault();setSent(true)}}>{sent?<div className="success"><Quote/><h3>You’re on the list.</h3><p>We’ll be in touch with the programme soon.</p></div>:<><label>Your name<input required placeholder="What should we call you?"/></label><label>Email address<input type="email" required placeholder="you@example.com"/></label><label>Phone number<input type="tel" placeholder="Optional"/></label><label>Anything you’d like to ask?<textarea placeholder="Tell us what you're looking for"></textarea></label><button className="register">Send enquiry <Send size={16}/></button></>}</form></div></section>
 </main><footer><div className="footer-brand"><span className="brand-mark"><span className="mark-orbit orbit-a"></span><span className="mark-orbit orbit-b"></span><Atom size={20}/></span> METALLUM <small>MME · 2026</small></div><p>Built around ideas worth sharing.</p><div><a href="#top">Instagram</a><a href="#top">LinkedIn</a><a href="#top">© 2026 Metallum</a></div></footer>
 {lightbox!==null&&<div className="lightbox" role="dialog" aria-modal="true" aria-label="Gallery image"><button className="close" onClick={()=>setLightbox(null)} aria-label="Close gallery"><X/></button><button className="prev" onClick={()=>setLightbox((lightbox-1+gallery.length)%gallery.length)} aria-label="Previous"><ChevronLeft/></button><div className={'lightbox-art '+gallery[lightbox][0]}><p>{gallery[lightbox][1]}</p></div><button className="next" onClick={()=>setLightbox((lightbox+1)%gallery.length)} aria-label="Next"><ChevronRight/></button></div>}</> }
createRoot(document.getElementById('root')).render(<App/>);
